### ISSUE TITLE
Repeat with dot echoes status message

### ISSUE THREAD

**Issue by lervag** [machakann/vim-columnmove#3]
If I do a columnwise motion delete, e.g. with `d<c-v><m-f>c` from the cursor at the first `a` in the following example:

```
aaa
bbb
ccc
```

And then repeat with dot `.`, then the plugin echoes `call columnmove#ftFT_executer()`. This happens with default settings.

**Comment by machakann** [comment]
I pushed fixed version (965680a0e5bae9d0ea65ffe9412fdd05c4b2e84f). Please check it!

**Comment by lervag** [comment]
It is fixed, thanks.
